language: php

php:
  - '7.1'
  - '7.2'

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source

script: vendor/bin/phpunit --coverage-text
