name: Build

on:
  push:
    paths-ignore: ['*.md']
  pull_request:
    branches: [master]
    paths-ignore: ['*.md']

jobs:
  test:
    name: Test (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1, 8.2]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Run the test suite
        run: vendor/bin/phpunit
